website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
from flask_login import login_user, login_required, logout_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db

authbp = Blueprint('auth', __name__ )

@authbp.route('/register', methods=['GET', 'POST'])
def register():
    register = RegisterForm()
    if (register.validate_on_submit()==True):
            uname = register.user_name.data
            pwd = register.password.data
            email = register.email_id.data
            phone = register.phone.data
            postcode = register.postcode.data
            user = User.query.filter_by(name=uname).first()
            if user:
                flash('Username already exists, please try another')
                return redirect(url_for('auth.register'))
            pwd_hash = generate_password_hash(pwd)
            new_user = User(name=uname, password_hash=pwd_hash, emailid=email, phone=phone, postcode=postcode)
            db.session.add(new_user)
            db.session.commit()
            return redirect(url_for('auth.register'))
    else:
        return render_template('user.html', form=register, heading='Register')

@authbp.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    error = None
    if(login_form.validate_on_submit()==True):
        user_name = login_form.user_name.data
        password = login_form.password.data
        user = User.query.filter_by(name=user_name).first()
        if user is None:
            error = 'Incorrect username or password'
        elif not check_password_hash(user.password_hash, password):
            error = 'Incorrect username or password'
        if error is None:
            login_user(user)
            return redirect(url_for('main.index'))
        else:
            flash(error)
    return render_template('user.html', form=login_form, heading='Login')

@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .models import Events, User, Tickets
from . import db
from flask_login import current_user

mainbp = Blueprint('main', __name__)

@mainbp.route('/')
def index():
    event = db.session.scalars(db.select(Events)).all()
    bebop=Events.query.filter(Events.eventCategory.ilike('%Bebop%')).all()
    blues=Events.query.filter(Events.eventCategory.ilike('%Blues%')).all()
    soul=Events.query.filter(Events.eventCategory.ilike('%Soul%')).all()
    return render_template('index.html', event=event, bebop=bebop, blues=blues, soul=soul)


@mainbp.route('/search')
def search():
    if request.args['search'] and request.args['search'] != "":
        print(request.args['search'])
        query = request.args['search']
        search=Events.query.filter(Events.name.ilike('%' + query + '%') | Events.description.ilike('%' + query + '%') ).all()
        return render_template('search.html', search=search, query=query)
    else:
        return redirect(url_for('main.index'))
    
@mainbp.route('/myEvents')
def myEvents():
    myevents = Events.query.filter(Events.event_manager_id == current_user.id).all()
    if not myevents:
        flash('You have no events. Create one first!', 'danger')
        return redirect(url_for('main.index'))
    else:
        return render_template('myEvents.html', myevents=myevents)
    

@mainbp.route('/userBookingHistory')
def history():
    ticket = db.session.query(Events, Tickets).join(Events, Tickets.event_id == Events.id).filter(Tickets.user_id == current_user.id).all()
    if ticket:
        return render_template('userBookingHistory.html', ticket=ticket)
    else:
        flash('You have not purchased any tickets for events.', 'danger')
        return redirect(url_for('main.index'))

@mainbp.errorhandler(404)
def not_found(e):
    return render_template('404.html')

@mainbp.errorhandler(400)
def bad_request(e):
    return render_template('400.html')

@mainbp.errorhandler(500)
def internal_error(e):
    return render_template('500.html')

website/templates/base.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>IAB207 Assignment 3</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="../static/style/index_style.css" type="text/css"/>
  </head>

<body>
    <!-- Header -->
    <header>

        <!-- Navbar 
        Add more to this based on feedback-->
        <nav class="navbar navbar-expand-lg bg-dark-subtle sticky-top">
            <div class="container-fluid">
                <a id="logo" class="navbar-brand" href="/">The Plastic Jazz <span class="logo-colored-word">Blues</span></a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"      aria-expanded="false" aria-label="Toggle navigation"></button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                      <!-- <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                      </li> -->

                      {% if current_user.is_authenticated %}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                         Welcome {{current_user.name}}</a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" aria-current="page" href="{{ url_for('main.history') }}">My Booking History</a></li>
                          <li><a class="dropdown-item" aria-current="page" href="{{ url_for('main.myEvents') }}">My Events</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" aria-current="page" href="{{ url_for('auth.logout') }}">Log Out</a></li>
                        </ul>
                      </li>

                      {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{{ url_for('auth.login') }}">Log In</a>
                        </li>
                      {% endif %}
                      
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('event.create') }}">Create Event</a>
                      </li>

                    </ul>
                    <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}" >
                      <input type="text" name="search" class="form-control flex-grow-1 my-1 mr-sm-2" id="SearchForm" placeholder="Search for Artists/Events...">
                      <button type="submit" class="flex-shrink-1 btn btn-primary my-1">Submit</button>
                    </form>
                  </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages() %}
        {% if messages %} <!-- check if there are any messages -->
          <div class="container-fluid">
            <div class="row mt-3 mb-3">
              <div class="col-md-12">
              {% for message in messages %} <!--loop through the messages-->
                <div class="alert alert-info">{{ message }}</div> <!--display as alert-->
              {% endfor %}
            </div>
          </div>
        </div>
        {% endif %}
        {% endwith %}

        {% block header %}

        {% endblock %}

    </header>

    {% block content %}
    
    {% endblock %}

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
            </a>
            <span class="mb-3 mb-md-0 text-muted">© 2023 The Plastic Jazz Blues</span>
        </div>
        <!-- Bootstrap Icons for Social Media accounts-->
        <a class = "icon-link" href="https://www.facebook.com/">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </svg>
        </a>
        <a class="icon-link" href="https://www.instagram.com/">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </svg>
        </a>
        <a class="icon-link" href="https://twitter.com/">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
          <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865l8.875 11.633Z"/>
        </svg>
        </a>
        <a class="icon-link" href="https://www.tiktok.com/en/">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-tiktok" viewBox="0 0 16 16">
          <path d="M9 0h1.98c.144.715.54 1.617 1.235 2.512C12.895 3.389 13.797 4 15 4v2c-1.753 0-3.07-.814-4-1.829V11a5 5 0 1 1-5-5v2a3 3 0 1 0 3 3V0Z"/>
        </svg>
        </a>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <span class="mb-3 mb-md-0 text-muted">Group 11</span>
        </ul>
        </footer>
    </div>

    <!-- Optional JavaScript -->
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

website/templates/index.html
<head>
  <link rel="stylesheet" href="../static/style/index_style.css" type="text/css"/>
</head>

{% extends 'base.html' %}

{% block header %}
    <!-- Bordered Hero -->
    <div class="container mt-5">
        <div class="row pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
          <div class="col p-3 p-lg-5 pt-lg-3">
            <h1 id="hero-header" class="display-4 fw-bold lh-1 text-body-emphasis text-center">Contribute to Australia's Jazz Scene Now!</h1>
            <p id="hero-body" class="lead text-center">The Plastic Jazz <span class="logo-colored-word">Blue</span>'s makes event management easy. Want to perform or host an event on behalf of a musician or group? Then create an event now!</p>
            <div class="d-grid gap-2 d-md-flex justify-content-md-center mb-4 mb-lg-3">
              <a href="{{ url_for('event.create') }}">
                <button type="button" class="btn btn-primary btn-lg px-4 me-md-2 fw-bold">Create Event</button>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div> 
{% endblock %}

{% block content %}      

      <!-- Categories using nav-pills to show relevant events -->
    <ul class="nav nav-pills mb-3 p-3 justify-content-center" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="pills-showall-tab" data-bs-toggle="pill" data-bs-target="#pills-showall" type="button" role="tab" aria-controls="pills-showall" aria-selected="true">Show All</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-bebop-tab" data-bs-toggle="pill" data-bs-target="#pills-bebop" type="button" role="tab" aria-controls="pills-bebop" aria-selected="false">Bebop</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-blues-tab" data-bs-toggle="pill" data-bs-target="#pills-blues" type="button" role="tab" aria-controls="pills-blues" aria-selected="false">Blues</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="pills-soul-tab" data-bs-toggle="pill" data-bs-target="#pills-soul" type="button" role="tab" aria-controls="pills-soul" aria-selected="false">Soul</button>
      </li>
    </ul>
    
    <div class="album">
      <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-showall" role="tabpanel" aria-labelledby="pills-showall" tabindex="0">
            <div class="card-group">
              {% for event in event %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
                  <div class="card-body">
                    <p class="card-text">
                      <h5>{{event.name}}</h5>
                      <small>{{event.eventDate}} {{event.eventTime}}</small>
                      <small class="text-muted red-text"><span class="start-price">Starts at AU ${{event.ticketPrice}}</span></small><br>
                      {{event.description}}
                    </p>
                    <div class="justify-content-between align-items-center">
                      <div class="row">
                        <div class="col-5">
                          <div class="btn-group">
                            <a href="{{ url_for('event.show', id=event.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                            </a>
                            {% if event.eventState == "Open" %}
                            <button type="button" class="btn btn-sm btn-success">Open</button>
                            {% elif event.eventState == "Expired" %}
                            <button type="button" class="btn btn-sm btn-danger">Expired</button>
                            {% elif event.eventState == "Sold Out" %}
                            <button type="button" class="btn btn-sm btn-warning">Sold Out</button>
                            {% else %}
                            <button type="button" class="btn btn-sm btn-danger">Cancelled</button>
                            {% endif %}
                          </div>
                        </div>
                        <div class="col-7">
                          <small class="text-muted">{{event.address1}}, {{event.address2}}, {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>  
          </div>
        
        
          <div class="tab-pane fade" id="pills-bebop" role="tabpanel" aria-labelledby="pills-bebop" tabindex="0">
            <div class="card-group">
              {% for event in bebop %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
                  <div class="card-body">
                    <p class="card-text">
                      <h5>{{event.name}}</h5>
                      <small>{{event.eventDate}} {{event.eventTime}}</small>
                      <small class="text-muted red-text"><span class="start-price">Starts at A${{event.ticketPrice}}</span></small><br>
                      {{event.description}}
                    </p>
                    <div class="justify-content-between align-items-center">
                      <div class="row">
                        <div class="col-5">
                          <div class="btn-group">
                            <a href="{{ url_for('event.show', id=event.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                            </a>
                            {% if event.eventState == "Open" %}
                            <button type="button" class="btn btn-sm btn-success">Open</button>
                            {% elif event.eventState == "Expired" %}
                            <button type="button" class="btn btn-sm btn-danger">Expired</button>
                            {% elif event.eventState == "Sold Out" %}
                            <button type="button" class="btn btn-sm btn-warning">Sold Out</button>
                            {% else %}
                            <button type="button" class="btn btn-sm btn-danger">Cancelled</button>
                            {% endif %}
                          </div>
                        </div>
                        <div class="col-7">
                          <small class="text-muted">{{event.address1}}, {{event.address2}}, {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>  
          </div>
        

          <div class="tab-pane fade" id="pills-blues" role="tabpanel" aria-labelledby="pills-blues" tabindex="0">
            <div class="card-group">
              {% for event in blues %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
                  <div class="card-body">
                    <p class="card-text">
                      <h5>{{event.name}}</h5>
                      <small>{{event.eventDate}} {{event.eventTime}}</small>
                      <small class="text-muted red-text"><span class="start-price">Starts at A${{event.ticketPrice}}</span></small><br>
                      {{event.description}}
                    </p>
                    <div class="justify-content-between align-items-center">
                      <div class="row">
                        <div class="col-5">
                          <div class="btn-group">
                            <a href="{{ url_for('event.show', id=event.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                            </a>
                            {% if event.eventState == "Open" %}
                            <button type="button" class="btn btn-sm btn-success">Open</button>
                            {% elif event.eventState == "Expired" %}
                            <button type="button" class="btn btn-sm btn-danger">Expired</button>
                            {% elif event.eventState == "Sold Out" %}
                            <button type="button" class="btn btn-sm btn-warning">Sold Out</button>
                            {% else %}
                            <button type="button" class="btn btn-sm btn-danger">Cancelled</button>
                            {% endif %}
                          </div>
                        </div>
                        <div class="col-7">
                          <small class="text-muted">{{event.address1}}, {{event.address2}}, {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>  
          </div>
        
      
          <div class="tab-pane fade" id="pills-soul" role="tabpanel" aria-labelledby="pills-soul" tabindex="0">
            <div class="card-group">
              {% for event in soul %}
              <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                  <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
                  <div class="card-body">
                    <p class="card-text">
                      <h5>{{event.name}}</h5>
                      <small>{{event.eventDate}} {{event.eventTime}}</small>
                      <small class="text-muted red-text"><span class="start-price">Starts at A${{event.ticketPrice}}</span></small><br>
                      {{event.description}}
                    </p>
                    <div class="justify-content-between align-items-center">
                      <div class="row">
                        <div class="col-5">
                          <div class="btn-group">
                            <a href="{{ url_for('event.show', id=event.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                            </a>
                            {% if event.eventState == "Open" %}
                            <button type="button" class="btn btn-sm btn-success">Open</button>
                            {% elif event.eventState == "Expired" %}
                            <button type="button" class="btn btn-sm btn-danger">Expired</button>
                            {% elif event.eventState == "Sold Out" %}
                            <button type="button" class="btn btn-sm btn-warning">Sold Out</button>
                            {% else %}
                            <button type="button" class="btn btn-sm btn-danger">Cancelled</button>
                            {% endif %}
                          </div>
                        </div>
                        <div class="col-7">
                          <small class="text-muted">{{event.address1}}, {{event.address2}} {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>  
          </div>
      </div>
    </div>

{% endblock %}

 



       

website/templates/myEvents.html
<head>
    <link rel="stylesheet" href="../static/style/index_style.css" type="text/css"/>
  </head>
  
  {% extends 'base.html' %}
  
  {% block header %}
  {% endblock %}
  
  {% block content %}  
  
  <div class="row text-center">
      <h3>My Events</h3>
  </div>
  
  <div class="album">
      <div class="card-group">
      {% for event in myevents %}
          <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                  <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
              <div class="card-body">
                  <p class="card-text">
                  <h5>{{event.name}}</h5>
                  <small>{{event.eventDate}} {{event.eventTime}}</small>
                  <small class="text-muted red-text"><span class="start-price">Starts at A${{event.ticketPrice}}</span></small><br>
                  {{event.description}}
                  </p>
                  <div class="justify-content-between align-items-center">
                      <div class="row">
                        <div class="col-7">
                          <div class="btn-group">
                            <a href="{{ url_for('event.show', id=event.id) }}">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                            </a>
                            <a href="{{ url_for('event.edit', event=event.id) }}">
                              <button type="button" class="btn btn-sm btn-outline-secondary">Edit Event</button>
                            </a>
                            {% if event.eventState == "Open" %}
                            <button type="button" class="btn btn-sm btn-success">Open</button>
                            {% elif event.eventState == "Expired" %}
                            <button type="button" class="btn btn-sm btn-danger">Expired</button>
                            {% elif event.eventState == "Sold Out" %}
                            <button type="button" class="btn btn-sm btn-warning">Sold Out</button>
                            {% else %}
                            <button type="button" class="btn btn-sm btn-danger">Cancelled</button>
                            {% endif %}
                          </div>
                        </div>
                        <div class="col-7">
                          <small class="text-muted">{{event.address1}}, {{event.address2}}, {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {% endfor %}
          </div> 
      </div> 
  </div>
  {% endblock %}
  

website/templates/search.html
<head>
  <link rel="stylesheet" href="../static/style/index_style.css" type="text/css"/>
</head>

{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}  

<div class="row text-center">
    <h3>You searched for...</h3>
    <h4> {{query}}</h4>
</div>

<div class="album">
    <div class="card-group">
    {% for event in search %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail" alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ event.image }}" alt="Event Image" data-holder-rendered="true">
            <div class="card-body">
                <p class="card-text">
                <h5>{{event.name}}</h5>
                <small>{{event.eventDate}} {{event.eventTime}}</small>
                <small class="text-muted red-text"><span class="start-price">Starts at A${{event.ticketPrice}}</span></small><br>
                {{event.description}}
                </p>
                <div class="justify-content-between align-items-center">
                    <div class="row">
                      <div class="col-5">
                        <div class="btn-group">
                          <a href="{{ url_for('event.show', id=event.id) }}">
                          <button type="button" class="btn btn-sm btn-outline-secondary">View Event</button>
                          </a>
                          <button type="button" class="btn btn-sm btn-success">Open</button>
                        </div>
                      </div>
                      <div class="col-7">
                        <small class="text-muted">{{event.address1}}, {{event.address2}}, {{event.city}}, {{event.state}}, {{event.postcode}}</small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
        </div> 
    </div> 
</div>
{% endblock %}

website/templates/user.html
<head>
    <link rel="stylesheet" href="../static/style/index_style.css">
</head>

{% extends "base.html" %}
{% import "bootstrap5/form.html" as wtf %}

{% block content %}

<div class="container-fluid">
<div class="page-header">
    <h4>{{heading}}</h4>
</div>

<!-- Form rendering is simple and easy if using bootstrap -->
<div class="col-md-6 ml-5">
{{wtf.render_form(form)}}
</div>

<!-- When you have login form, then do show the user a link to register -->
{% if heading|lower =='login' %}
<div class="col-md-4 mb-5 ml-5">
    <p>New user? <a href="{{ url_for('auth.register') }}">Click here to register</a>.</p>
</div>
{% endif %}
</div>
{% endblock %}